### ISSUE TITLE
No such file: translate_dataset_few_shot.py

### ISSUE THREAD

**Issue by anonymoususerr1** [juletx/phd#1]
When I run the first self translate example (using XGLM 7.5B), I get the following error:

```[Errno 2] No such file or directory
envs/selftranslate/bin/python: can't open file '.../self-translate/lm_eval/lm-evaluation-harness/translate_dataset_few_shot.py

**Comment by juletx** [comment]
That file is in this directory: https://github.com/juletx/self-translate/tree/main/translate/scripts. So you need to run the example from that path. You can also find an example script to run all the translations of XGLM models at https://github.com/juletx/self-translate/blob/main/translate/scripts/xglm/translate_few_shot_xglm.slurm. You will need to change the environment and transformers cache path.

**Comment by anonymoususerr1** [comment]
Thanks for the quick reply. After applying the correct path I got the following error. Do you have any idea why this happens?

```RuntimeError: No executable batch size found, reached zero.```

**Comment by juletx** [comment]
Which GPU do you have? This error means that accelerate did not find a batch size that can fit on your GPU. You will need choose a smaller model if the 7.5B model does not fit.

**Comment by anonymoususerr1** [comment]
I already tried 4.5B model and reducing the batch size to 32. Btw, I am using 8 A100(40GB) GPUs.

**Comment by juletx** [comment]
I don't know why you get that error. I run all the experiments on A100 80GB, so it should work on yours too. Is the model loading correctly? The only difference is that I used slurm to select a single GPU. Can you try selecting a single GPU?

**Comment by anonymoususerr1** [comment]
Thanks for the suggestion. Single GPU works fine.

**Comment by juletx** [comment]
No problem. Reach out if you have other issues.
